### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by calebfaruki** [gtramontina/stripe-angular#6]
```javascript
angular.module('stripe', []).directive('stripeForm', ['$window',
function($window) {

  var directive = { restrict: 'A' };
  directive.link = function(scope, element, attributes) {
    if(!$window.Stripe){
      throw 'stripeForm is not included in the HTML.';
    }
    var form = angular.element(element);
    form.bind('submit', function() {
      var button = form.find('button');
      button.prop('disabled', true);

      // can either pass an object or can parse a form with data-stripe attributes
      $window.Stripe.createToken(form[0], function() {
        // after getting token, reenable form
        button.prop('disabled', false);
        console.log(scope[attributes.stripeForm]);console.log(scope);
        var args = arguments;
        scope.$apply(function() {
          scope[attributes.stripeForm].apply(scope, args);
        });
      });
    });
  };
  return directive;
}]);
```

Here is the full error: 

    TypeError: Cannot read property 'apply' of undefined
    at http://localhost:8100/lib/stripe-angular/stripe-angular.js:22:39
    at Scope.$eval (http://localhost:8100/lib/ionic/js/ionic.bundle.js:20326:28)
    at Scope.$apply (http://localhost:8100/lib/ionic/js/ionic.bundle.js:20424:23)
    at http://localhost:8100/lib/stripe-angular/stripe-angular.js:21:15
    at Object.e.request.success (https://js.stripe.com/v2/:1:1697)
    at window.(anonymous function) (https://js.stripe.com/v2/:1:10496)
    at https://api.stripe.com/v1/tokens?card[number]=4242424242424242&card[cvc]=12…er_agent=stripe.js%2F4871079&callback=sjsonp1418772119600&_method=POST:1:1

This code is exactly the same as what exists in your stripe-angular.js file as far as I can tell. What would cause this issue to happen?

There were also a few gaps in the setup of stripe-angular in my project. Not sure if this is an error on my part of if there is something else missing from the docs here.

**Comment by gtramontina** [comment]
Sorry for the silence... Were you ever able to solve it?

Regarding you `console.log`ging scope, there will be no `attributes` key there. Log this instead: `console.log(attributes)`, as that's what we're interested in. You should see, at least, `stripeForm: "stripeResponseHandler"`.

**Comment by seibar** [comment]
@gtramontina I ran across this as well. In my case it was caused by a dot in my binding, e.g.:

`<form stripe-form="vm.submitOrder">`

Replacing line 14, `scope[attributes.stripeForm].apply(scope, args);` in stripe-angular.js with: `scope.$eval(attributes.stripeForm).apply(scope, args);` fixes it for me.

**Comment by gtramontina** [comment]
Ohh I see it now... :grinning: 
@seibar your solution seems to be the right one anyway! Mind a pull request?

**Comment by seibar** [comment]
@gtramontina sure thing!
